image: maven:latest

stages:
    - auth
    - test
    - deploy
    - unitTest

# Get token
gcp-authenticate:
  stage: auth
  image: "google/cloud-sdk:latest"
  script:
    # Auth GCP with Service Account
    - export GOOGLE_APPLICATION_CREDENTIALS=$(echo $GCP_SA_CRED)
    - echo ${GOOGLE_APPLICATION_CREDENTIALS} > creds.json
    - export GOOGLE_APPLICATION_CREDENTIALS=creds.json
    - "gcloud config set project $GCP_PROJECT_ID"
    - "gcloud config set account $GCP_SA"
    - "gcloud auth login --cred-file=creds.json"
    - "export TOKEN=$(gcloud auth print-access-token)"
    - "curl --request PUT --header PRIVATE-TOKEN:$API_PAT https://gitlab.com/api/v4/projects/54316165/variables/TOKEN --form value=$TOKEN > response.json"
    - "echo Token Generated Successfully"

#Static code analysis
test:
  image: node:latest
  stage: test
  script:
    # Run apigeelint
    - npm install -g apigeelint
    - apigeelint -f table.js --profile apigeex -s ./apiproxy

# Deploy Proxy
mvn-deploy-proxy:
    stage: deploy
    needs: ["test","gcp-authenticate"]
    script:
        - "mvn -Pgoogleapi -Pdeployonly install -Dapigee.config.options=create -DproxyName=$PROXY_NAME -Denv=$APIGEE_ENV -Dorg=$GCP_PROJECT_ID -Dtoken=$TOKEN"

# Unit test with Cucuber.js and Gherkin
mvn-unit-test:
    image: node:latest
    stage: unitTest
    needs: ["mvn-deploy-proxy"]
    script:
      - pwd
      - ls
      - cd api_everardoproxy_mocks
      - npm run init-api
      - npm run test
      - export COUNT_FAILED=$(grep -o -i failed tests/features/resultados/cucumber_report.json| wc -l)
      - echo $COUNT_FAILED