variables:
    APIGEE_ORG: "bjuarezintacademy"
    APIGEE_ENV: "eval"
    EVAL_HOST: 34.36.220.25.nip.io
    TOKEN: $TOKEN
    GOOGLE_CLOUD_PROJECT: $GOOGLE_CLOUD_PROJECT
    GOOGLE_CLOUD_PROJECT_NUMBER: $GOOGLE_CLOUD_PROJECT_NUMBER
    SERVICE_ACCOUNT_EMAIL: "sa-gitlab-pipeline@bjuarezintacademy.iam.gserviceaccount.com"

image: maven:latest

# GCP_SERVICE_ACCOUNT is stored in Gitlab CI/CD variable settings
# GCP_SERVICE_ACCOUNT variable, type file :O

cache:
    paths:
        - .m2/repository/
        - /target/
        - /node_modules/

stages:
    - install-dependencies
    - deploy

#get token


# install dependencies
install-dependencies:
    stage: install-dependencies
    image: node:12-alpine
    script:
        - npm install --silent --no-fund
        - pwd
        - ls

# Deploy Proxy
mvn-package:
    stage: deploy
    script:
        - if [ "$AUTHOR_EMAIL" == "" ]; then AUTHOR_EMAIL="$GITLAB_USER_EMAIL"; fi
        - mvn process-resources -Pgoogleapi -Dcommit=$GIT_COMMIT -Dbranch=$GIT_BRNACH -Dauthor=$AUTHOR_EMAIL

#mvn-config:
#    stage: deploy
#    needs: ["mvn-package"]
#    script:
#        - mvn apigee-enterprise:configure -Pgoogleapi -Dorg=$GOOGLE_CLOUD_PROJECT -Denv=$APIGEE_ENV

mvn-deploy-proxy:
    stage: deploy
    needs: ["mvn-package"]
    script:
        - pwd
        - ls
        - echo $APIGEE_ENV
        - echo $GOOGLE_CLOUD_PROJECT
        - mvn -Pgoogleapi -Pdeployonly install -Dapigee.config.options=create -Denv=$APIGEE_ENV -Dorg=$GOOGLE_CLOUD_PROJECT -Dtoken=$TOKEN
