image: maven:latest

stages:
    - auth
    - deploy

#get token
get-token:
  stage: auth
  image: "google/cloud-sdk:latest"
  before_script:
    # Authenticate Google Cloud Service Account
    - export GOOGLE_APPLICATION_CREDENTIALS=$(echo $GCP_SA_CRED)
    - echo ${GOOGLE_APPLICATION_CREDENTIALS} > creds.json
    - export GOOGLE_APPLICATION_CREDENTIALS=creds.json
  script:
    - "gcloud config set project $GCP_PROJECT_ID"
    - "gcloud config set account $GCP_SA"
    - "gcloud auth login --cred-file=creds.json"
    - "export TOKEN=$(gcloud auth print-access-token)"
    - "curl --request PUT --header PRIVATE-TOKEN:$API_PAT https://gitlab.com/api/v4/projects/54316165/variables/TOKEN --form value=$TOKEN"

# Deploy Proxy
mvn-deploy-proxy:
    stage: deploy
    needs: ["get-token"]
    script:
        - "mvn -Pgoogleapi -Pdeployonly install -Dapigee.config.options=create -DproxyName=$PROXY_NAME -Denv=$APIGEE_ENV -Dorg=$GCP_PROJECT_ID -Dtoken=$TOKEN"
