image: maven:latest

stages:
    - auth
    - deploy

variables:
  TOKEN: dummyvalue

cache:
    paths:
        - .m2/repository/
        - target/
        - node_modules/

.before_setup:
  before_script:
    # Authenticate Google Cloud service account
    - export GOOGLE_APPLICATION_CREDENTIALS=$(echo $GCP_SA_CRED)
    - echo ${GOOGLE_APPLICATION_CREDENTIALS} > creds.json
    - export GOOGLE_APPLICATION_CREDENTIALS=creds.json

#get token
get-token:
  stage: auth
  extends: .before_setup
  image: "google/cloud-sdk:latest"
  script:
    - "gcloud config set project $GCP_PROJECT_ID"
    - "gcloud config set account $GCP_SA"
    - "gcloud auth login --cred-file=creds.json"
    - "export TOKEN=$(gcloud auth print-access-token)"
    - "echo $TOKEN"

# Deploy Proxy
mvn-deploy-proxy:
    stage: deploy
    needs: ["get-token"]
    script:
        - mvn -Pgoogleapi -Pdeployonly install -Dapigee.config.options=create -Denv=$APIGEE_ENV -Dorg=$GCP_PROJECT_ID -Dtoken=$TOKEN
